ChimeraTK/DeviceAccess

- device/include/ReadAnyGroup.h
- tests/executables_src/testAsyncRead.cpp
The `waitAny` method now returns a notification object instead of a `TransferElementID`. This way, the actual reading of the data update can be deferred until later.
As a side effect, this makes the code cleaner, because now it is not necessary any longer to call `ReadAnyGroup::postRead()`. Instead, the notification object has an `accept()` method that takes care of this. As this method is also called from the destructor of the notification object, it is no longer possible to "forget" to call `postRead()`.
@mhier: This is the change that we discussed offline. As a side effect, polled elements are now only processed when using `readAny()`. Code using `waitAny()` directly has to also call `processPolled()`. This is cleaner than polling these elements from `postRead()` (which was an …
> Change ReadAnyGroup::waitAny() to allow deferred processing

- device/include/DataConsistencyGroup.h
- device_backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
- doc/dataConsistencyGroup.dox
- doc/mainpage.dox
- examples/dataConsistencyGroup.cpp
- tests/executables_src/testDataConsistencyGroup.cpp
> Consistency group

- CMakeLists.txt
- device_backends/LogicalNameMapping/include/LNMAccessorPlugin.h
- device_backends/LogicalNameMapping/include/LogicalNameMapParser.h
- device_backends/LogicalNameMapping/src/LNMAccessorPlugin.cc
- device_backends/LogicalNameMapping/src/LogicalNameMapParser.cc
- doc/logicalNameMapper.dox
- tests/CMakeLists.txt
- tests/executables_src/testLMapMathPlugin.cpp
- tests/mathPlugin.xlmap
Resolves #47 (lmap math plugin)
> Lnm math plugin

- device_backends/LogicalNameMapping/include/LogicalNameMappingBackend.h
- device_backends/SharedDummy/include/SharedDummyBackend.h
- device_backends/Subdevice/include/SubdeviceBackend.h
- device_backends/include/DeviceBackendImpl.h
- device_backends/include/DummyBackend.h
- tests/executables_src/testAsyncRead.cpp
- tests/executables_src/testDevice.cpp
- tests/executables_src/testSubdeviceBackend.cpp
> removed: _hasError and isFunctional() from DeviceBackendImpl

- README.md
On my first try to build this, I had to figure out where to find the dependencies. Maybe it's a good idea linking to them in the README.
> Mention dependencies in README

- device_backends/include/ExceptionDummyBackend.h
extend ExceptionDummyBackend so that all poll-type registers are
decorated with ExceptionDummyPollDecorator which allows to set data
validity of individual registers to invalid
> introduce ExceptionDummyPollDecorator

- device_backends/SharedDummy/include/SharedDummyBackend.h
- device_backends/include/DummyBackend.h
- device_backends/include/DummyBackendBase.h
- device_backends/include/NumericAddressedBackendRegisterAccessor.h
- device_backends/src/DummyBackendBase.cc
- tests/executables_src/testDummyBackend.cpp
> No more crtp

- CMakeLists.txt
- device_backends/DummyBackend/include/DummyBackend.h
have to discuss whether the changes should not come with a new major vesion though...
> increase minor version

- device/include/TransferElementAbstractor.h
- device/include/TransferGroup.h
- device/src/TransferGroup.cc
- device_backends/NumericAddressedBackend/include/NumericAddressedInterruptDispatcher.h
- device_backends/include/AsyncAccessorManager.h
- device_backends/include/AsyncNDRegisterAccessor.h
- device_backends/include/UnifiedBackendTest.h
- device_backends/src/AsyncAccessorManager.cc
- tests/executables_src/testNumericAddressedBackendUnified.cpp
- tests/executables_src/testTransferGroup.cpp
This is the simple version of the implementation, there is a follow-up ticket #9541 to refactor the code as discussed
> Fix transfer group invalid merge

- device_backends/NumericAddressedBackend/include/NumericAddressedBackendRegisterAccessor.h
- device_backends/NumericAddressedBackend/src/NumericAddressedBackend.cc
- device_backends/SharedDummy/include/SharedDummyBackend.h
- device_backends/SharedDummy/src/SharedDummyBackend.cc
- device_backends/SharedDummy/src/SharedMemoryManager.cc
- device_backends/include/AsyncAccessorManager.h
- tests/executables_src/testSharedDummyBackendUnified.cpp
- tests/executables_src/testTransferGroup.cpp
- tests/include/sharedDummyHelpers.h
- tests/scripts/testSharedDummyBackendPidManagement.sh
- tests/sharedDummyUnified.map
- tests/unitTestsNotUnderCtest/testSharedDummyBackendUnifiedExt.cpp
> SharedDummyBackend remote interrupt trigger

- device/include/TransferElementID.h
- device_backends/NumericAddressedBackend/include/NumericAddressedLowLevelTransferElement.h
- tests/CMakeLists.txt
- tests/executables_src/testNumericAddressedBackendRegisterAccessor.cpp
There were a couple of problems when building on macOS (12.6), as described in #281. This MR fixes these problems.
> Fix build on macOS

- device_backends/uio/include/UioAccess.h
gcc 11 (on Ubuntu 22.04) complains..
> fix missing include

- tests/executables_src/testDoubleBuffering.cpp
BOOST.Test is not thread-safe, e.g. BOOST_CHECK macro cannot be called concurrently from threads. So we buffer the check results in the main thread.
> call BOOST_CHECK only in main thread

- CMakeLists.txt
fix problems which cause errors with new cmake concept
> cmake: small fixes

- examples/CMakeLists.txt
- examples/numeric_address.cpp
> fix: make example compile again

- CMakeLists.txt
> threads is not required explicitly

- device_backends/LogicalNameMapping/include/LNMAccessorPlugin.h
- device_backends/LogicalNameMapping/include/LNMBackendBitAccessor.h
- device_backends/LogicalNameMapping/include/LogicalNameMappingBackend.h
- device_backends/LogicalNameMapping/src/LNMAccessorPlugin.cc
- device_backends/LogicalNameMapping/src/LNMBitRangeAccessPlugin.cc
- device_backends/LogicalNameMapping/src/LNMForcePollingReadPlugin.cc
- device_backends/LogicalNameMapping/src/LNMForceReadOnlyPlugin.cc
- device_backends/LogicalNameMapping/src/LNMMonostableTriggerPlugin.cc
- device_backends/LogicalNameMapping/src/LNMMultiplierPlugin.cc
- device_backends/LogicalNameMapping/src/LogicalNameMapParser.cc
- device_backends/NumericAddressedBackend/include/FixedPointConverter.h
- doc/logicalNameMapper.dox
- tests/CMakeLists.txt
- tests/bitRangeReadPlugin.xlmap
- tests/executables_src/testLMapBackendUnified.cpp
- tests/executables_src/testLMapBitRangePlugin.cc
- tests/unifiedTest.xlmap
- util/src/Utilities.cpp
- lmap: Remove template helper classes
- lmap: Fix typos
- LMAP: Add BitRange accessor plugin
> Introduce LMAP bitRange plugin

- doc/design_AsyncNDRegisterAcessor_and_NumericAddressedBackend.dox
Is it worth doing a bug fix release for this?
> fix: docu for interrupts in map files

- device_backends/LogicalNameMapping/include/LNMMathPlugin.h
- device_backends/LogicalNameMapping/src/LNMMathPlugin.cc
- tests/executables_src/testLMapBackendUnified.cpp
- lock order inversion
- unlocking of unlocked mutex
> fix: tsan issues

- device_backends/uio/include/UioBackend.h
- device_backends/uio/src/UioAccess.cc
e.g. on ARM64, memcpy will result in more than 1 write to an address, causing multiple triggers to the FPGA for this data to happen
> fix: Memcopy for mmio is bad, do manual copy

- doc/logicalNameMapper.dox
Was one level too high, caused weird folding in the online docs
> fix(docs): Indentation level for forcePollingRead

- device_backends/uio/src/UioAccess.cc
E.g. well-known names for changing /dev/uioX entries
> feat(uio): Support symlinked device files

- device_backends/NumericAddressedBackend/include/NumericAddressedBackend.h
- device_backends/NumericAddressedBackend/src/NumericAddressedBackend.cc
- device_backends/include/AsyncAccessorManager.h
- device_backends/include/AsyncDomain.h
- device_backends/include/AsyncDomainImpl.h
- device_backends/include/TriggeredPollDistributor.h
- device_backends/include/UnifiedBackendTest.h
- device_backends/include/VariableDistributor.h
- device_backends/src/AsyncAccessorManager.cc
- device_backends/src/TriggerDistributor.cc
- device_backends/src/TriggeredPollDistributor.cc
- device_backends/uio/include/UioBackend.h
- device_backends/uio/src/UioAccess.cc
- device_backends/uio/src/UioBackend.cc
- device_backends/xdma/include/EventFile.h
- device_backends/xdma/include/XdmaBackend.h
- device_backends/xdma/src/EventFile.cc
- device_backends/xdma/src/XdmaBackend.cc
- tests/executables_src/testLMapBitRangePlugin.cc
- tests/executables_src/testUioBackendUnified.cpp
- tests/uioBackendTest.mapp
This merge request contains several commits: The test as the main feature and multiple fixes to make the test pass. This resolves several race conditions and memory access violations in the NumericAddressedBackend and the UIO backend.
Note: It might be easier to review the commits separately.
> feat(uio): unified backend test

- tests/executables_src/testExceptionDummyDevice.cc
- tests/test3.map
https://redmine.msktools.desy.de/issues/8606
> tests: move DataValidity test from ApplicationCore

- include/DataConsistencyGroup.h
> feat: allow inspection of DataConsistencyGroup contents

- backends/DummyBackend/src/DummyBackend.cc
- backends/LogicalNameMapping/src/LNMBitRangeAccessPlugin.cc
- backends/Rebot/src/RebotProtocol0.h
- backends/Rebot/src/RebotProtocol1.h
- backends/Rebot/src/RebotProtocolImplementor.h
- backends/xdma/src/DeviceFile.cc
- backends/xdma/src/EventFile.cc
- include/NumericAddressedLowLevelTransferElement.h
- tests/executables_src/testAsyncVarAndHierarchicalInterruptsUnified.cpp
- tests/executables_src/testBackendFactory.cpp
- tests/executables_src/testLMapMathPlugin.cpp
- tests/executables_src/testNumericAddressedBackendRegisterAccessor.cpp
- tests/executables_src/testPcieBackend.cpp
- tests/executables_src/testRebotConnectionTimeouts.cpp
- tests/executables_src/testRunTimeBackendLoading.cpp
Adapt to minor changes with clang-format-19
> chore: Run clang-format

- backends/DummyBackend/include/DummyBackendRegisterCatalogue.h
- backends/DummyBackend/src/DummyBackendRegisterCatalogue.cc
- include/BackendRegisterCatalogue.h
- include/NumericAddressedRegisterCatalogue.h
- include/VersionNumber.h
- src/NumericAddressedRegisterCatalogue.cc
- tests/CMakeLists.txt
I recommend review by commit, as they are unrelated.
> Minor things

- backends/DummyBackend/include/DummyBackend.h
- backends/DummyBackend/include/DummyBackendBase.h
- backends/DummyBackend/include/ExceptionDummyBackend.h
- backends/DummyBackend/src/DummyBackend.cc
- backends/DummyBackend/src/ExceptionDummyBackend.cc
- backends/SharedDummy/include/SharedDummyBackend.h
- backends/SharedDummy/src/SharedDummyBackend.cc
- doc/design_AsyncNDRegisterAcessor_and_NumericAddressedBackend.dox
- doc/spec_DataConsistencyKeyMapping.dox
- include/BackendRegisterCatalogue.h
- include/NumericAddressedBackend.h
- include/NumericAddressedRegisterCatalogue.h
- include/async/AsyncAccessorManager.h
- include/async/DataConsistencyKey.h
- include/async/DataConsistencyRealm.h
- include/async/DataConsistencyRealmStore.h
- include/async/SubDomain.h
- include/async/TriggeredPollDistributor.h
- include/async/VariableDistributor.h
- src/BackendRegisterCatalogue.cc
- src/DummyBackendBase.cc
- src/NumericAddressedBackend.cc
- src/NumericAddressedRegisterCatalogue.cc
- src/async/DataConsistencyRealm.cc
- src/async/DataConsistencyRealmStore.cc
- src/async/TriggeredPollDistributor.cc
- tests/executables_src/testDataConsistencyRealm.cpp
- tests/include/helperFunctions.h
- tests/testDataConsistencyRealm.map
Note: is already based in #468 - only the last commit is new.
> Data consistency realm

- tools/chimeratk-lmap-editor
- **chore(lmap-editor): Format code**
- **fix(lmap-editor): Properly mark regex strings**
- **fix(lmap-editor): Accept empty modules when saving**
- **feat(lmap-editor): Allow removing multiple items**
- **feat(lmap-editor): Support Del for removing items**
- **feat(lmap-editor): Support new-style sequences**
- **feat(lmap-editor): Do not ask user twice on exit**
- **chore(lmap-editor): Add copyright header**
> chore: Various lmap-editor improvements

- backends/LogicalNameMapping/include/LNMBackendBitAccessor.h
This was a forgotten change on a branch...
> feat(LNM): improve logic_error messages for bit accessors

- CMakeLists.txt
This PR bumps the version to 03.21.00
> chore: Bump version to 03.21.00

- CMakeLists.txt
This PR bumps the version to 03.23.00
> chore: Bump version to 03.23.00
