ChimeraTK/DeviceAccess

- CMakeLists.txt
- device_backends/CMakeLists.txt
- device_backends/src/BackendFactory.cc
- examples/custom_backend_registration/CMakeLists.txt
- fileparsers/src/parserUtilities.cc
- tests/CMakeLists.txt
In the original version the Device Access library does not compile on macOS. This is a pity, because the Control System Adapter depends on this library and there are a number of scenarios where using the code makes sense on non-Linux systems.
The problems that appear when compiling on macOS can be put in two categories: problems caused by using LLVM instead of GCC and problems caused by different APIs (BSD vs Linux). This PR addresses both kind of issues.
In order to make the build work on macOS, the call to the Linux-specific `get_current_dir_name` function has been replaced with a call to the `getcwd` function, which works on both platforms. The PCIe backend and tests that depend on it are only built on Linux because there is no reasonable way how it could be ported to other platforms. …
> Make Device Access compile on macOS

- device_backends/include/DummyBackend.h
- device_backends/src/DummyBackend.cc
The dummy backend did not use any synchronization mechanism when reading and writing. This meant that devices backed by the device backend could show strange behavior when accessing them from multiple threads.
This patch introduces a mutex that is acquired for all read and write operations. The mutex is not acquired when attaching callbacks or setting address ranges as read only, as those functionality is specific to the dummy backend and thus not exposed by the `Device` class.
> Make dummy backend thread safe.

- tests/executables_src/testSharedDummyBackend.cpp
- tests/unitTestsNotUnderCtest/testSharedDummyBackendExt.cpp
This PR fixes the name collision discussed in #19.
> Avoid name collision of "label" types (issue #19).

- device/include/ReadAnyGroup.h
- device/include/TransferElementAbstractor.h
Allows to create a ReadAnyGroup from pointers to TransferElements (or derived classes like the NDRegisterAccessor), while currently one needs to have a copy of a TransferElementAbstractor (resp. derived classes like ScalarRegisterAccessor). This is mostly useful for implementations within the framework.
Somehow the constructor of TransferElementAbstractor was made protected, so it could only be used by derived classes. This has now been changed to public. Now anyone can crate TransferElementAbstractor objects from pointers to TransferElements, which is useful in cases where the UserType is unknown (and thus a ScalarRegisterAccessor etc. could not be created).
> Read any group from pointers

- device/src/Device.cc
- device_backends/SharedDummy/src/SharedDummyBackend.cc
- device_backends/pcie/src/PcieBackend.cc
- device_backends/src/DummyBackend.cc
- tests/executables_src/testDummyBackend.cpp
- tests/executables_src/testLMapBackend.cpp
- tests/executables_src/testPcieBackend.cpp
- tests/executables_src/testSharedDummyBackend.cpp
- tests/executables_src/testSubdeviceBackend.cpp
- tests/unitTestsNotUnderCtest/testRebotBackend.cpp
When a device throws an error while reading RegisterAccessor ApllictaionCore modules that use that RegisterAccessors are stopped.
To recover ApplicationCore will call open on the Device. But since isOpen() will still return true the device will not be reopened and e.g. a client conncetion can not be recovered.
> Remove testing if device is open.

- doc/spec_TransferElement.dox
* B.3.2.3 specified return value of write operations
* B.8.2 and B.8.2.3 specified how data is obtained via the queue continuation
* C.5 Existence and shape of a register must be checked in the constructor (not at runtime)
* C.5.2.4 Removed throwing logic error when requesting an accessor with larger data type for writing.
> Transfer element v1.0 rc9

- doc/spec_TransferElement.dox
- tests/executables_src/testTransferGroup.cpp
I had to re-introduce runtime_errors in preXxx. They are needed for the exception handling.
This has consequences for the behaviour of the the TransferGroup.
> Transfer element v1.0 rc11

- doc/spec_TransferElement.dox
The boost::bad_numeric_cast exception has been removed. Instead the data is clamped into the data range than the data validity is set to faulty.
In addition, the ChimeraTK::logic_error is not allowed in the constructor any more. The data is always clamped.
With these changes the read and write direction have symmetric behaviour.
> Transfer element v1.0 rc13

- device_backends/include/UnifiedBackendTest.h
Build with g++ 9.3.0 produces a wall of text about 'no user-provided default constructor' (see abbreviated example below)
```
../device_backends/include/UnifiedBackendTest.h: In instantiation of ‘ChimeraTK::UnifiedBackendTest<VECTOR_OF_REGISTERS_T>::test_B_8_5() [with VECTOR_OF_REGISTERS_T = boost::mpl::v_item<SubdeviceBackendUnifiedTestSuite::Regs3Type<SubdeviceBackendUnifiedTestSuite::MyArea1>, boost::mpl::v_item<SubdeviceBackendUnifiedTestSuite::Regs3Type<SubdeviceBackendUnifiedTestSuite::MyRegister1>, boost::mpl::vector<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, 0>, 0>]::<lambda(auto:60)> [with auto:60 = …
```
> Fix compiler warnings

- device_backends/include/DummyRegisterAccessor.h
- device_backends/include/NumericAddressedBackend.h
- device_backends/src/NumericAddressedBackend.cc
- fileparsers/include/RegisterInfoMap.h
- fileparsers/src/MapFileParser.cpp
- fileparsers/src/RegisterInfoMap.cpp
The XDMA driver allows transparent access to the whole FPGA memory, which can be a 64-bit address space on the bigger boards.
This patch changes the address type to uint64_t. It keeps the existing 32-bit interface for existing backends.
> Change address type to uint64_t for new backends

- device_backends/include/NumericAddressedBackend.h
- device_backends/include/NumericAddressedLowLevelTransferElement.h
- device_backends/src/NumericAddressedBackend.cc
`NumericAddressedLowLevelTransferElement` shouldn't know details about which BAR values are valid and which ones are not. This patch delegates that check to the `NumericAddressedBackend` implementation. By default, it performs the same check that was done in `NumericAddressedLowLevelTransferElement` constructor before. Now a subclass of `NumericAddressedBackend` can override that check and re-define which BAR values are valid.
> Move bar index check to NumericAddressedBackend

- device_backends/Subdevice/include/SubdeviceRegisterAccessor.h
- device_backends/Subdevice/src/SubdeviceBackend.cc
- device_backends/Subdevice/src/SubdeviceRegisterAccessor.cc
- tests/CMakeLists.txt
- tests/SubdeviceMuxedArea.map
- tests/executables_src/testSubdeviceBackend.cpp
- tests/executables_src/testSubdeviceBackendUnified.cpp
This fixes #177 (on github)
Note: This changes existing behaviour in one aspect: previously, the
address written to the address register was incremented in steps of 4
for subsequent low-level transfers of the same high-level register (like
a byte address). This does not make much sense, and likely no use case
relied on this behaviour. It should be noted though that this behaviour
was tested. The tests have been changed accordingly (and extended with
the new functionality).
> SubdeviceBackend 2regs/3regs mode: add support for data areas.

- device_backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
The lmap catalogue was no longer being updated with information from its target backends. This caused the observed issues with the math plugin being forced into the wrong direction.
> fix lmap catalogue not updating from target info

- device/include/Device.h
- device/include/ForwardDeclarations.h
Remove Device::getRegisterAccessor declaration (definition already gone)
and RegisterAccessor forward declaration
> Remove RegisterAccessor from public headers

- device/include/VersionNumber.h
Does not change any existing behaviour, since the copy constructor was actually already trivial. Now, VersionNumber can be e.g. used in an std::atomic.
See my comments in #247 (may still be pending...)
> make VersionNumber trivially copyable

- device_backends/xdma/include/XdmaBackend.h
- device_backends/xdma/src/XdmaBackend.cc
Changes `XdmaBackend::_intfFromBar()` to return a reference to the chosen interface, instead of a pointer. If `_ctrlIntf` is chosen (by BAR 0) but empty for some reason, an exception is thrown instead of a `nullptr` returned.
Eliminates a (theoretical) error case involving an unhandled `nullptr`.
> xdma: _intfFromBar(): return reference, not pointer

- device/include/ReadAnyGroup.h
If another exception is on the queue while peeking for a DiscardValueException, this is thrown as well.
It has to be caught and discarded. Otherwise it shows up at the wrong place.
It stays on the queue and is handles later.
> ReadAnyGroup: Catch runtime_errors while peeking for DiscardValueExceptions

- device/include/ReadAnyGroup.h
Fixed thread leak caused by not suppressing boost::thread_terminate when peeking the read queue.
> ReadAnyGroup: Fixed thread leak

- CMakeLists.txt
- As the variable content of the xdma CtrlIntf class has changed I don"t know if
it's binary compatible, so I increased the minor version, not the patch level
> Increased minor version number

- device/include/DataConsistencyGroup.h
also for MatchingMode::none, update method must return false if given TransferElement is not member
of the group.
Used e.g. in DoocsAdapter, for slowly updating process variables which
are have a macropulse source.
> fix result of DataConsistencyGroup::update

- device_backends/LogicalNameMapping/include/LNMBackendVariableAccessor.h
- device_backends/LogicalNameMapping/src/LNMMathPlugin.cc
- device_backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
Previously, the MathPlugin would ignore incoming updates from parameters
if they were pushed in activateAsyncRead(), even if they were written
between the call to open() and activateAsyncRead(). This is a severe
issue, since ApplicationCore is first recovering all device registers
and then calling activateAsyncRead().
Note: The fix needs also a change in ApplicationCore, since it
previously writes the recovery values with the VersionNumber from the
last write, which was before the call to open().
Another solution to this problem would be to accept variable parameters
in the MathPlugin which have been written at least once after creating
the backend (in contrast to after the last call to open()). This
solution was rejected, since it would cause the MathPlugin's target
register to be …
> fix LNM math plugin push parameters in device recovery (cf. #9961)

- device/include/VoidRegisterAccessor.h
Needed in ApplicationCore for the inversion of control
> Add default constructor to VoidRegisterAccessor

- device/include/VoidRegisterAccessor.h
The constructor should not be explicit, since implicit conversion is
expected.
> fix VoidRegisterAccessor constructor

- tests/executables_src/testDummyBackend.cpp
size_t might be 32bit there, we can fall back to the old deprecated functions as well as the new uint64_t ones. Make clear we use the new ones by explicitly casting the size_t variables to uint64_t
> Fix ambiguity for read/write on 32bit platforms

- device_backends/uio/src/UioAccess.cc
was failing on Tumbleweed (gcc 12)
> fix missing include

- device/include/ReadAnyGroup.h
In ApplicationCore we frequently pass derived objects of the
TransferElementAbstractor class with additional data members to the
ReadAnyGroup constructor. The std::initializer_list uses copy sematics,
hence the objects were sliced (i.e. copied into base class instances
which lack the additional data members). By using an
std::initialiser_list of std::reference_wrapper, only references are
copied and slicing is avoided at that point.
Note that this change mainly avoids the linter warning. The slicing at
that place was harmless, since the additional data members are not
accessed by base class functionality.
> avoid object slicing in ReadAnyGroup

- device_backends/LogicalNameMapping/include/LogicalNameMapParser.h
- device_backends/LogicalNameMapping/src/LogicalNameMapParser.cc
- tests/executables_src/testLMapMathPlugin.cpp
- tests/mathPlugin.xlmap
This simplifies writing formulas containing lots of <, > and & which then don't need XML escaping
> lmap: Allow CDATA for parameters

- tests/executables_src/testDummyBackend.cpp
- tests/executables_src/testExceptionDummyDevice.cc
- tests/executables_src/testRebotConnectionTimeouts.cpp
- tests/executables_src/testRebotHeartbeatCount.cpp
The boost test library is linked. Using the included version leads to a violation of the one definition rule and causes double free corruptions.
> Don't use 'included' boost test library.

- device_backends/pcie/src/PcieBackend.cc
The bar offsets start at bit 60 upwards, passing down the offsets
through off_t requires the 64bit variants to end up in kernel correctly
> Enable 64bit io for pcie backend

- util/src/ProcessManagement.cpp
getlogin() sometimes seems to have issues to properly retrieve the
username
> Use getwuid/geteuid instead of getlogin()

- device_backends/LogicalNameMapping/include/LNMDoubleBufferPlugin.h
- device_backends/NumericAddressedBackend/include/NumericAddressedBackendMuxedRegisterAccessor.h
std::iterator is deprecated. Instead, the 5 iterator traits should be listed separately.﻿
> fix g++-12 compiler warnings

- device_backends/LogicalNameMapping/src/LogicalNameMapParser.cc
- device_backends/NumericAddressedBackend/include/NumericAddress.h
Just escape the strings as pre-formatted
> Fix warnings from Doxygen for unsupported tags

- doc/logicalNameMapper.dox
- enable_push_parameters is only for write mode
- it is, however, suggested for most cases with ApplicationCore
- for variables, initial values are then not used
- constants are also allowed
> clarify documentation of math plugin

- tests/executables_src/testMappedImage.cc
- tests/executables_src/testTypeChangingDecorator.cpp
- util/include/MappedImage.h
- util/include/TypeChangingDecorator.h
use "" for searching includes that are from DeviceAccess itself. Changes affect the files which have been moved from ControlSystemAdapter to DeviceAccess.
> fix: header include syntax

- tests/executables_src/testMappedImage.cc
- tests/executables_src/testTypeChangingDecorator.cpp
asan saw 'double free' issues which were due to using boost unit test framework at the same time, as included variant and as linked variant. Decide for linked variant.
> fix: solve asan test issues

- CMakeLists.txt
That is not necessary, libxml++ should pull that in and it is not a public dependency of it
Upstreaming of Yocto patch
> fix: Drop explicit dependency to glib-2.0

- CMakeLists.txt
- device_backends/xdma/include/XdmaBackend.h
- device_backends/xdma/src/XdmaBackend.cc
- push type accessors can be requested before opening the device
- no event file is opened if no push type accessors exist
> fix(xdma): event files opened in the wrong place

- device_backends/LogicalNameMapping/include/internal/LNMMathPluginFormulaHelper.h
- device_backends/LogicalNameMapping/src/LNMBackendVariableAccessor.cc
- device_backends/LogicalNameMapping/src/LNMMathPlugin.cc
- device_backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
- device_backends/include/UnifiedBackendTest.h
- tests/executables_src/testLMapBackendUnified.cpp
- tests/executables_src/testLMapMathPluginPushPars.cc
This replaces the earlier hotfix with a better implementation.
As a (positive) side effect of the new fix, push-type parameters of math plugins now work independently of the async read activation state.
> fix: rethrow old exceptions by math plugin after recovery

- device/include/DataDescriptor.h
- device/src/DataDescriptor.cpp
- util/include/SupportedUserTypes.h
This code is basically moved from ApplicationCore to
make it generally available (Python bindings need it
as well)
> feat: obtain minimum data type from DataDescriptor

- device_backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
Clang does not support the use of variables from a structured bind
in lambdas yet.
> fix: structured bind in lambdas

- device_backends/LogicalNameMapping/include/LNMAccessorPlugin.h
- device_backends/LogicalNameMapping/src/LNMBitRangeAccessPlugin.cc
- doc/logicalNameMapper.dox
- tests/bitRangeReadPlugin.xlmap
- tests/executables_src/testLMapBitRangePlugin.cc
- tests/unifiedTest.xlmap
When using the math plugin, it can be that the underlying data is no
longer guaranteed to be integral, so we use the FPC instead.
Unfortunately this will limit the bit range to 32 for now
> fix: Use FixedPointConverter to convert input data

- device_backends/Rebot/src/Connection.cc
The implicit capture of *this, when the capture default is =, is deprecated (since C++20).
> Avoid implicit copy in lambda when only 'this' is needed

- device_backends/NumericAddressedBackend/src/NumericAddressedBackend.cc
- device_backends/include/AsyncDomainsContainer.h
- device_backends/include/TriggerDistributor.h
The TriggerDistributor has become a template class of BackendSpecificDataType. However, the VariableDistributor insisde was still hard-coded to nullptr_t.
> fix: VariableDistributor type is always nullptr_t

- device_backends/DummyBackend/include/DummyInterruptTriggerAccessor.h
- device_backends/DummyBackend/include/ExceptionDummyBackend.h
- device_backends/include/UnifiedBackendTest.h
- device_backends/src/DummyInterruptTriggerAccessor.cc
- tests/executables_src/testUioBackendUnified.cpp
- fix: dummy bugs
testDummyBackendUnified was failing since the DummyInterruptTriggerAccessor was correctly reporting that it is not readable.
The failure was due to a bug in the ExceptionDummyBackend. The decorator of the ExceptionDummyBackend was also masking a wrong value
in the user buffer of the DummyInterruptTriggerAccessor.
﻿- fix(UnifiedBackendTest): catalogue test disabled for dummy accessors
The DummyInterruptTriggerAccessor reporting the wrong readability was not detected because the Unified backend test was not sensitive.
The workaround has been removed since the dummy accessors are in the catalogue since some time.
- fix: compiler warning
> fix failing test

- backends/DummyBackend/include/DummyBackendBase.h
- backends/DummyBackend/include/ExceptionDummyBackend.h
- backends/DummyBackend/src/ExceptionDummyBackend.cc
- include/NumericAddressedBackend.h
- include/VirtualFunctionTemplate.h
- src/DummyBackendBase.cc
- src/async/MuxedInterruptDistributor.cc
- tests/executables_src/testUnifiedTypeChangingDecorator.cpp
- tests/executables_src/testVirtualFunctionTemplate.cc
This fixes a huge chunk of the LTO errors we are seeing on noble.
Frankly it is also unclear why it worked in the first place
> fix: Provide explicit template specialisations

- CMakeLists.txt
- backends/DummyBackend/src/DummyBackendRegisterCatalogue.cc
- include/NumericAddressedBackendRegisterAccessor.h
- include/async/GenericMuxedInterruptDistributor.h
- include/async/MuxedInterruptDistributor.h
- include/async/SubDomain.h
- src/async/GenericMuxedInterruptDistributor.cc
- src/async/MuxedInterruptDistributor.cc
- tests/CMakeLists.txt
- tests/executables_src/testGenericMuxedInterruptDistributor.cpp
- tests/irq_test.mapp
The GenericMuxedInterruptDistributor handles hierarchical interrupts on an interrupt controller and distributes them to the according to sub domain. The implementation was tested on the Xilinx AXI4 interrupt controller, but it is extensible to work with many types of interrupt controllers.
> feat: implement GenericMuxedInterruptDistributor

- backends/uio/include/UioAccess.h
For some reason this is necessary on Yocto master
> fix(uio-backend): Add missing include

- include/SupportedUserTypes.h
- tests/executables_src/testUtilities.cpp
userTypeToNumeric_impl<std::string, NUMERIC> was modified to be interpret both decimal and hexidecimal representations of numbers into numeric types. Hexidecimal numbers are identified by 'x' or 'X' as the 2nd character.
This allows userTypeToUserType<UserType,string> to be fed strings representations of hexidecimal numbers and correctly interpret them. 
This was tested for correct behavior of decimal and hexidecimal integers into int, int64, uint, int8_t, uint8_t, and bool.
> feat: userTypeToUserType supports HEX strings

- backends/LogicalNameMapping/src/LNMBackendVariableAccessor.cc
- doc/spec_TransferElement.dox
- include/TransferElement.h
- tests/executables_src/testTransferElement.cpp
This is required to terminate ApplicationCore applications properly when a poll-type input (connected internally) is waiting for initial values (which uses a blocking call to future_queue::pop_wait()).
Note: This goes along with https://github.com/ChimeraTK/ApplicationCore/pull/393
> fix: allow TransferElement::interrupt() without wait_for_new_data

- backends/xdma/src/XdmaBackend.cc
The XDMA backend called internally close() when a recovery of an
exception was attempted. In particular if the recovery was still
unsuccessful, the device was then left in the closed state leading to
logic_error exceptions in subsequent read/write operations. This caused
ApplicationCore applications to terminate immediately after an exception
of an XDMA device was seen.
This is now fixed by using a dedicated flag for the backend opened
status which is independent of the underlying interface status.
> fix(xdma): backend must not close itself on error

- backends/SharedDummy/include/SharedDummyBackend.h
- backends/SharedDummy/src/SharedDummyBackend.cc
- backends/SharedDummy/src/SharedMemoryManager.cc
The SharedDummy backend was crashing with a
boost::interprocess::lock_exception when a previous instance was
interrupted in the wrogn place. This is now fixed by catching the
exception and removing the shared memory segment (which is then broken
anyway).
> fix(sharedDummy): catch exception after previous instance interrupted

- backends/LogicalNameMapping/src/LNMMathPlugin.cc
- tests/executables_src/testLMapMathPlugin.cpp
This creates rather annoying issues when used with a TransferGroup, in
which case the exception message is totally invisible ("terminate called
without an active exception").
A more permanent solution should execute checks when the formula is
compiled, so the logic_error can be thrown earlier.
> fix(lmap): temporary fix for logic_errors in postRead with math plugin

- backends/LogicalNameMapping/src/LogicalNameMappingBackend.cc
- doc/spec_TransferElement.dox
- include/UnifiedBackendTest.h
- include/async/DomainImpl.h
- fix: async::Domain re-sends values
- fix: LMAP backend re-sends values
- improve the specification
- add unified backend test
> fix: calling activateAsycRead when asyncRead active

- tests/executables_src/testSubdeviceBackend.cpp
This is an attempt to debug a spurious, hard to reproduce race
condition, which has been seen only on Jenkins so far.
> chore: use BOOST_TEST for more diagnostics in one test

- doc/spec_TransferElement.dox
- include/TransferGroup.h
- src/TransferGroup.cc
- tests/executables_src/testTransferGroup.cpp
- tests/include/TransferElementTestAccessor.h
This is no longer necessary, since the subsequent handling of all relevant exception types is appropriate also for logic_errors. It was also an issue, since in ApplicationCore the ExceptionHandlingDecorator prevents initiating transfers if the Device is temporarily closed while executing an init handler, but the TransferGroup throws the logic_error anyway.
This change comes with a spec change, since this was actually specified explicitly, and consequently tests for these spec points are removed as well.
> fix: don't throw logic_error in TransferGroup directly (#14286)

- backends/SharedDummy/include/SharedDummyBackend.h
- backends/SharedDummy/src/SharedDummyBackend.cc
- backends/SharedDummy/src/SharedMemoryManager.cc
- include/Utilities.h
- src/Utilities.cpp
- tests/executables_src/testSharedDummyBackendUnified.cpp
- tests/include/sharedDummyHelpers.h
- tests/unitTestsNotUnderCtest/testSharedDummyBackendExt.cpp
- tests/unitTestsNotUnderCtest/testSharedDummyBackendUnifiedExt.cpp
generate hash from address and all cdd parameters, even when unused. Like this, different cdds result in different shm instances. Put shm segment name creation to Utilities so its available for test code.
NOTE: This change breaks compatibility for shm dummy communication with previous DeviceAccess versions.
> fix: shm dummy instance id hash

- backends/LogicalNameMapping/include/LNMAccessorPlugin.h
- backends/LogicalNameMapping/src/LNMAccessorPlugin.cc
- backends/LogicalNameMapping/src/LNMTagModifierPluign.cc
- doc/logicalNameMapper.dox
- include/SystemTags.h
- tests/executables_src/testLMapTagModifier.cc
- tests/tagModifierPlugin.xlmap
Add isStatusOutput and hasReverseRecovery plugins as a more condensed
way to add well-known ChimeraTK tags to registers
> feat(lmap): Convenience plugins for system tags

- include/CopyRegisterDecorator.h
- src/TransferGroup.cc
The accessor should only ever be used in TransferGroup and that does
handle preRead of the target itself.
Also add an assertion such that a read transfer on the decorator does
not occur
> fix: Do noting in CopyRegisterDecorator::doPreRead
